/*********************************************************************************
# Copyright (c) 2012, CyberPoint International, LLC
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the CyberPoint International, LLC nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CYBERPOINT INTERNATIONAL, LLC BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**********************************************************************************/


/*! \file EM_Algorithm.h
*   \brief Function prototypes for EM algorithm routines
*   \author Elizabeth Garbee
*   \date Summer 2012
*/
#ifndef EM_AGORITHM_H
#define EM_ALGORITHM_H

#include <limits>
#include <cstring>

#include "Matrix.h"

using namespace std;

/************************************************************************************************
** EM FUNCTION "PUBLIC" DECLARATIONS
************************************************************************************************/


/*! \brief EM: train a Gaussian Mixture model on a given data set.
*
*
@param[in] n number of data points
@param[in] m dimensionality of data
@param[in] k number of clusters
@param[out] X data
@param[out] sigma_matrix vector of matrix pointers generated by the caller of EM that holds the sigmas calculated
@param[out] mu_matrix matrix that holds the mu approximations
@param[out] Pks local copy of the matrix generated by the caller of EM that holds the Pk's calculated
@return the log likelihood (density) of the data (or std::numeric_limits::infinity() on error)
*/
double EM(int n, int m, int k, double *X, vector<Matrix*> &sigma_matrix, Matrix &mu_matrix, Matrix &Pks);

/*! \brief ParseCSV converts csv or svm-format data and converts it to a double array.
*
@param[in] m dimensionality of the d
@param[in] n the number of data points
@param[out] data pointer to pre-allocated m X n double array. data returned here.
@param[out] labels pointer to pre-allocated array of size n, for svm format, or null, for csv format. labels returned here.
@return 1 for success, 0 for an error or failure.
*/
int ParseCSV(char *file_name,  int n, int m, double *data, int * labels = NULL);

/*! \brief pdf: compute the log of the probability of the given data point
*
*
@param[in] m dimensionality of data
@param[in] k number of clusters
@param[in] X data point
@param[in] sigma_matrix vector of covariance matrices from EM or adpated call
@param [in] mu_matrix cluster means returned from EM or adapted call
@param [in] Pks cluster weights returned by EM or adapted call
@return log likelihood or (or std::numeric_limits::infinity() on error)
*/
double pdf(int m, int k, const double *X, const vector<Matrix*> &sigma_matrix,
		const Matrix &mu_matrix, const Matrix &Pks);

#endif //EM_ALGORITHM_HEADER

